import { db, sqlite } from './connection.ts'
import { apis, categories } from './schema.ts'
import { eq } from 'drizzle-orm'

sqlite.exec(`
  CREATE TABLE IF NOT EXISTS apis (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    "group" TEXT NOT NULL DEFAULT 'Build',
    countries TEXT NOT NULL DEFAULT '[]',
    provider TEXT NOT NULL,
    source TEXT,
    source_url TEXT,
    tier TEXT NOT NULL DEFAULT 'open',
    kind TEXT NOT NULL DEFAULT 'api',
    auth TEXT NOT NULL DEFAULT 'none',
    copyable INTEGER DEFAULT 1,
    pricing TEXT NOT NULL DEFAULT 'free',
    docs TEXT,
    base_url TEXT,
    frequency TEXT,
    coverage TEXT,
    note TEXT,
    attributes TEXT,
    created_at TEXT NOT NULL DEFAULT (current_timestamp),
    updated_at TEXT NOT NULL DEFAULT (current_timestamp),
    submitted_by TEXT,
    verified_at TEXT
  );
  CREATE INDEX IF NOT EXISTS idx_apis_category ON apis(category);
  CREATE INDEX IF NOT EXISTS idx_apis_tier ON apis(tier);
  CREATE INDEX IF NOT EXISTS idx_apis_auth ON apis(auth);
  CREATE INDEX IF NOT EXISTS idx_apis_pricing ON apis(pricing);

  CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    group_name TEXT NOT NULL DEFAULT 'Build',
    icon TEXT,
    sort_order INTEGER DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
  );

  CREATE TABLE IF NOT EXISTS api_tags (
    api_id TEXT NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    data TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    submitted_by TEXT,
    submitted_at TEXT NOT NULL DEFAULT (current_timestamp),
    reviewed_by TEXT,
    reviewed_at TEXT,
    review_notes TEXT
  );

  CREATE TABLE IF NOT EXISTS api_snippets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    api_id TEXT NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
    language TEXT NOT NULL,
    code TEXT NOT NULL
  );
`)

const existing = db.select({ id: apis.id }).from(apis).limit(1).get()
if (existing) {
  console.log('Database already seeded, skipping.')
  process.exit(0)
}

const catData = [
  { name: 'Weather', slug: 'weather', groupName: 'Data', icon: 'cloud', sortOrder: 1 },
  { name: 'Transport', slug: 'transport', groupName: 'Mobility', icon: 'bus', sortOrder: 2 },
  { name: 'Finance', slug: 'finance', groupName: 'Finance', icon: 'dollar', sortOrder: 3 },
  { name: 'Government', slug: 'government', groupName: 'Public', icon: 'building', sortOrder: 4 },
  { name: 'Health', slug: 'health', groupName: 'Public', icon: 'heart', sortOrder: 5 },
  { name: 'Education', slug: 'education', groupName: 'Data', icon: 'book', sortOrder: 6 },
  { name: 'Telecom', slug: 'telecom', groupName: 'Infrastructure', icon: 'wifi', sortOrder: 7 },
  { name: 'Maps', slug: 'maps', groupName: 'Mobility', icon: 'map', sortOrder: 8 },
  { name: 'E-commerce', slug: 'ecommerce', groupName: 'Business', icon: 'cart', sortOrder: 9 },
  { name: 'Social', slug: 'social', groupName: 'Media', icon: 'chat', sortOrder: 10 },
]

db.insert(categories).values(catData).run()
console.log(`Inserted ${catData.length} categories`)

const apiData = [
  {
    id: 'my-weather',
    slug: 'my-weather',
    title: 'Malaysia Weather API',
    description: 'Real-time weather data, forecasts, and warnings for all states in Malaysia. Updated every 3 hours from MET Malaysia.',
    category: 'Weather',
    group: 'Data',
    countries: '["MY"]',
    provider: 'MET Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.met.gov.my/v1',
    docs: 'https://developer.met.gov.my',
    frequency: 'Every 3 hours',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'sg-weather',
    slug: 'sg-weather',
    title: 'Singapore Weather API',
    description: 'Hourly weather updates, 24-hour forecast, and rainfall data across Singapore. Provided by NEA.',
    category: 'Weather',
    group: 'Data',
    countries: '["SG"]',
    provider: 'NEA Singapore',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.nea.gov.sg/v1',
    docs: 'https://developer.nea.gov.sg',
    frequency: 'Hourly',
    coverage: 'Singapore',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'id-weather',
    slug: 'id-weather',
    title: 'Indonesia Weather API',
    description: 'BMKG weather data covering all provinces in Indonesia. Includes earthquake alerts and marine forecasts.',
    category: 'Weather',
    group: 'Data',
    countries: '["ID"]',
    provider: 'BMKG Indonesia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.bmkg.go.id/v1',
    docs: 'https://data.bmkg.go.id',
    frequency: 'Every 6 hours',
    coverage: 'Indonesia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'th-weather',
    slug: 'th-weather',
    title: 'Thailand Weather API',
    description: 'TMD weather forecasts, storm warnings, and air quality data for all regions of Thailand.',
    category: 'Weather',
    group: 'Data',
    countries: '["TH"]',
    provider: 'TMD Thailand',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.tmd.go.th/v1',
    docs: 'https://data.tmd.go.th',
    frequency: 'Every 3 hours',
    coverage: 'Thailand',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-ktmb',
    slug: 'my-ktmb',
    title: 'KTM Train Schedule API',
    description: 'Real-time KTM Komuter and ETS train schedules, fares, and route data for Peninsular Malaysia.',
    category: 'Transport',
    group: 'Mobility',
    countries: '["MY"]',
    provider: 'KTM Berhad',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.ktmb.com.my/v2',
    docs: 'https://developer.ktmb.com.my',
    frequency: 'Real-time',
    coverage: 'Peninsular Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'sg-lta',
    slug: 'sg-lta',
    title: 'LTA Transport API',
    description: 'Comprehensive Singapore transport data: bus arrivals, taxi availability, traffic cameras, ERP rates.',
    category: 'Transport',
    group: 'Mobility',
    countries: '["SG"]',
    provider: 'LTA Singapore',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://datamall.lta.gov.sg/v1',
    docs: 'https://datamall.lta.gov.sg',
    frequency: 'Real-time',
    coverage: 'Singapore',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-bnm',
    slug: 'my-bnm',
    title: 'Bank Negara Malaysia API',
    description: 'Official exchange rates, interest rates, and economic indicators from Bank Negara Malaysia.',
    category: 'Finance',
    group: 'Finance',
    countries: '["MY"]',
    provider: 'Bank Negara Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.bnm.gov.my/v2',
    docs: 'https://developer.bnm.gov.my',
    frequency: 'Daily',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'sg-mas',
    slug: 'sg-mas',
    title: 'MAS Financial Data API',
    description: 'Singapore financial statistics, exchange rates, bond yields, and monetary authority data from MAS.',
    category: 'Finance',
    group: 'Finance',
    countries: '["SG"]',
    provider: 'Monetary Authority of Singapore',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.mas.gov.sg/v1',
    docs: 'https://developer.mas.gov.sg',
    frequency: 'Daily',
    coverage: 'Singapore',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-dosm',
    slug: 'my-dosm',
    title: 'Malaysia Statistics API',
    description: 'Population, economic, trade, and social statistics from the Department of Statistics Malaysia (DOSM).',
    category: 'Government',
    group: 'Public',
    countries: '["MY"]',
    provider: 'Department of Statistics Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.dosm.gov.my/v1',
    docs: 'https://developer.dosm.gov.my',
    frequency: 'Quarterly',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-myhealth',
    slug: 'my-myhealth',
    title: 'MyHealth API',
    description: 'Malaysia health data: hospital locations, clinic wait times, disease surveillance, and healthcare statistics.',
    category: 'Health',
    group: 'Public',
    countries: '["MY"]',
    provider: 'Ministry of Health Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.myhealth.gov.my/v1',
    docs: 'https://developer.myhealth.gov.my',
    frequency: 'Daily',
    coverage: 'Malaysia',
    copyable: 0,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'th-moph',
    slug: 'th-moph',
    title: 'Thailand Health API',
    description: 'Ministry of Public Health data: hospital capacity, disease outbreaks, vaccination records, and health indicators.',
    category: 'Health',
    group: 'Public',
    countries: '["TH"]',
    provider: 'Ministry of Public Health Thailand',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.moph.go.th/v1',
    docs: 'https://developer.moph.go.th',
    frequency: 'Daily',
    coverage: 'Thailand',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-moe',
    slug: 'my-moe',
    title: 'Malaysia Education API',
    description: 'School directory, exam results, enrollment data, and education statistics from MOE Malaysia.',
    category: 'Education',
    group: 'Data',
    countries: '["MY"]',
    provider: 'Ministry of Education Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.moe.gov.my/v1',
    docs: 'https://developer.moe.gov.my',
    frequency: 'Yearly',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-tm',
    slug: 'my-tm',
    title: 'TM One API',
    description: 'Telekom Malaysia network status, coverage maps, and broadband availability checker for Malaysia.',
    category: 'Telecom',
    group: 'Infrastructure',
    countries: '["MY"]',
    provider: 'Telekom Malaysia',
    tier: 'commercial',
    kind: 'api',
    auth: 'oauth',
    pricing: 'freemium',
    baseUrl: 'https://api.tm.com.my/v2',
    docs: 'https://developer.tm.com.my',
    frequency: 'Real-time',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: null,
  },
  {
    id: 'sg-singtel',
    slug: 'sg-singtel',
    title: 'Singtel API Gateway',
    description: 'Singapore telecom APIs: SMS, voice, network edge, and IoT connectivity services from Singtel.',
    category: 'Telecom',
    group: 'Infrastructure',
    countries: '["SG"]',
    provider: 'Singtel',
    tier: 'commercial',
    kind: 'api',
    auth: 'oauth',
    pricing: 'paid',
    baseUrl: 'https://api.singtel.com/v1',
    docs: 'https://developer.singtel.com',
    frequency: 'Real-time',
    coverage: 'Singapore',
    copyable: 1,
    verifiedAt: null,
  },
  {
    id: 'my-jkr',
    slug: 'my-jkr',
    title: 'JKR Map Services API',
    description: 'Malaysia public works department spatial data: road networks, flood maps, and infrastructure GIS layers.',
    category: 'Maps',
    group: 'Mobility',
    countries: '["MY"]',
    provider: 'Jabatan Kerja Raya Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.jkr.gov.my/v1',
    docs: 'https://developer.jkr.gov.my',
    frequency: 'Monthly',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'id-bps',
    slug: 'id-bps',
    title: 'Indonesia Map API',
    description: 'Badan Pusat Statistik geospatial data: administrative boundaries, census data, and regional statistics.',
    category: 'Maps',
    group: 'Mobility',
    countries: '["ID"]',
    provider: 'BPS Indonesia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.bps.go.id/v1',
    docs: 'https://data.bps.go.id',
    frequency: 'Yearly',
    coverage: 'Indonesia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-shopee',
    slug: 'my-shopee',
    title: 'Shopee Malaysia API',
    description: 'Shopee Malaysia product catalog, pricing, order management, and seller analytics for e-commerce integration.',
    category: 'E-commerce',
    group: 'Business',
    countries: '["MY"]',
    provider: 'Shopee',
    tier: 'commercial',
    kind: 'api',
    auth: 'oauth',
    pricing: 'paid',
    baseUrl: 'https://partner.shopeemobile.com/api/v2',
    docs: 'https://developer.shopee.com',
    frequency: 'Real-time',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: null,
  },
  {
    id: 'my-grab',
    slug: 'my-grab',
    title: 'Grab API',
    description: 'Grab rides, food delivery, and parcel services API for Southeast Asia. Real-time pricing and driver tracking.',
    category: 'Transport',
    group: 'Mobility',
    countries: '["MY","SG","ID","TH"]',
    provider: 'Grab Holdings',
    tier: 'commercial',
    kind: 'api',
    auth: 'oauth',
    pricing: 'paid',
    baseUrl: 'https://api.grab.com/v1',
    docs: 'https://developer.grab.com',
    frequency: 'Real-time',
    coverage: 'Southeast Asia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-kkmnow',
    slug: 'my-kkmnow',
    title: 'KKMNOW API',
    description: 'Malaysia healthcare data API: COVID-19 updates, hospital bed capacity, and disease monitoring statistics.',
    category: 'Health',
    group: 'Public',
    countries: '["MY"]',
    provider: 'KKM Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'none',
    pricing: 'free',
    baseUrl: 'https://api.kkmnnow.gov.my/v1',
    docs: 'https://data.kkmnnow.gov.my',
    frequency: 'Daily',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-ipr',
    slug: 'my-ipr',
    title: 'MyIPO Patent API',
    description: 'Malaysia intellectual property database: patent filings, trademark registrations, and industrial design searches.',
    category: 'Government',
    group: 'Public',
    countries: '["MY"]',
    provider: 'MyIPO Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.myipo.gov.my/v1',
    docs: 'https://developer.myipo.gov.my',
    frequency: 'Daily',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'sg-onemap',
    slug: 'sg-onemap',
    title: 'OneMap SG API',
    description: 'Singapore authoritative map API: geocoding, reverse geocoding, routing, and thematic map layers.',
    category: 'Maps',
    group: 'Mobility',
    countries: '["SG"]',
    provider: 'Singapore Land Authority',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.onemap.gov.sg/v2',
    docs: 'https://www.onemap.gov.sg',
    frequency: 'Real-time',
    coverage: 'Singapore',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'th-dlt',
    slug: 'th-dlt',
    title: 'Thailand DLT Vehicle API',
    description: 'Thai Department of Land Transport vehicle registration data, driving license verification, and transport permits.',
    category: 'Government',
    group: 'Public',
    countries: '["TH"]',
    provider: 'DLT Thailand',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.dlt.go.th/v1',
    docs: 'https://developer.dlt.go.th',
    frequency: 'Daily',
    coverage: 'Thailand',
    copyable: 0,
    verifiedAt: new Date().toISOString(),
  },
  {
    id: 'my-tng',
    slug: 'my-tng',
    title: 'Touch \'n Go eWallet API',
    description: 'Malaysia\'s leading e-wallet API for payments, top-ups, transaction history, and merchant settlement.',
    category: 'Finance',
    group: 'Finance',
    countries: '["MY"]',
    provider: 'Touch \'n Go Digital',
    tier: 'commercial',
    kind: 'api',
    auth: 'oauth',
    pricing: 'paid',
    baseUrl: 'https://api.tngdigital.com.my/v1',
    docs: 'https://developer.tngdigital.com.my',
    frequency: 'Real-time',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: null,
  },
  {
    id: 'my-jpj',
    slug: 'my-jpj',
    title: 'JPJ Public API',
    description: 'Road Transport Department Malaysia: vehicle ownership checks, license validity, summons records, and PUSPAKOM data.',
    category: 'Government',
    group: 'Public',
    countries: '["MY"]',
    provider: 'JPJ Malaysia',
    tier: 'open',
    kind: 'api',
    auth: 'apiKey',
    pricing: 'free',
    baseUrl: 'https://api.jpj.gov.my/v1',
    docs: 'https://developer.jpj.gov.my',
    frequency: 'Real-time',
    coverage: 'Malaysia',
    copyable: 1,
    verifiedAt: new Date().toISOString(),
  },
]

for (const api of apiData) {
  db.insert(apis).values(api).run()
}

console.log(`Inserted ${apiData.length} APIs`)
console.log('Seed complete!')
process.exit(0)
